content.root=/home/sean/umschulung-work/FIAE-Exam-Part-1-Content
quarkus.http.cors=true
quarkus.http.cors.origins=https://seanconroy-dev.github.io,http://localhost:4321
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with,x-API-key

# Flyway
quarkus.flyway.migrate-at-start=true

#DEV database - H2 in-memory
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:mem:fiae_exam_part_1;DB_CLOSE_DELAY=-1
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=

# Hibernate
%dev.quarkus.hibernate-orm.database.generation=none
%prod.quarkus.hibernate-orm.database-orm.database.generation=none

# Production database - PostgesSQL via environment variables
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=${DB_URL}
%prod.quarkus.datasource.username=${DB_USER}
%prod.quarkus.datasource.password=${DB_PASSWORD}

#
admin.token=${ADMIN_TOKEN:dev-admin-token}